server:
  port: 8080

spring:
  application:
    name: api-gateway
  main:
    allow-circular-references: true
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1

        - id: ticket-service
          uri: lb://ticket-service
          predicates:
            - Path=/api/tickets/**,/api/orders/**
          filters:
            - StripPrefix=1

        - id: event-service
          uri: lb://event-service
          predicates:
            - Path=/api/events/**
          filters:
            - StripPrefix=1

        - id: booking-service
          uri: lb://booking-service
          predicates:
            - Path=/api/bookings/**
          filters:
            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    com.netflix.discovery: DEBUG