name: Build & Test

on:
  push:
    paths:
      - "api-gateway/**"
      - "auth-service/**"
      - "booking-service/**"
      - "discovery-service/**"
      - "event-service/**"
      - "ticket-service/**"
  pull_request:
    paths:
      - "api-gateway/**"
      - "auth-service/**"
      - "booking-service/**"
      - "discovery-service/**"
      - "event-service/**"
      - "ticket-service/**"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [api-gateway, auth-service, booking-service, discovery-service, event-service, ticket-service]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Build with Maven
        run: cd ${{ matrix.service }} && mvn clean compile -DskipTests

      - name: Run unit tests
        run: cd ${{ matrix.service }} && mvn test

      - name: Package JAR
        run: cd ${{ matrix.service }} && mvn package -DskipTests

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.service }}-jar
          path: ${{ matrix.service }}/target/*.jar
          retention-days: 1